name: Gate

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Clone
      uses: actions/checkout@v4
    
    - name: Setup
      uses: dtolnay/rust-toolchain@stable
    
    - name: Build
      run: time make build VERBOSE=true PROFILE=release

    - name: Test
      run: time make test PROFILE=release    

    - name: Verbose Test
      run: time RUST_BACKTRACE=1 make test VERBOSE=true PROFILE=release  
