name: Makefile list targets

on:
  workflow_dispatch:

jobs:
  makefile-list-targets:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Run make
        run: make
